### PR TITLE
Expand GuildRenameEvent to include the new Guild name

### PR DESCRIPTION
**Pull request by kosakriszi**
I need to know the new guild name to rename some regions that my plugin creates when a guild is renamed

### CODE REVIEW

**Comment by darbyjack** [comment]
Nice catch, completely missed this. Did you want me to add in a prefix event too?

**Comment by kosakriszi** [comment]
Yeah that'd be great, and if it isn't too much to ask, an owner change event as well!

**Comment by darbyjack** [comment]
Sure thing! I'll add those in tonight and that can be tomorrow's update.

**Comment by darbyjack** [comment]
Should be good to go https://github.com/guilds-plugin/Guilds/commit/08f91b06faf3db6ea3e5ad319f53dca8c8e9b934

**Pull request closed without merging**
